### ISSUE TITLE
Wrong wording in email params

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#1022]
In emails param, the term 'auteur' is used but it is misleading. When I write an email which will be sent by my assistant, 'auteur' refers to the assistant, not the user.

The labels param should be 'votre prénom' instead of 'prénom de l'auteur'

same for others.

**Comment by FranzPoize** [comment]
It's auteur of the comment it might be the customer's name if he is the one who commented. Auteur and destinataire are only available for comment added emails.

**Comment by yannickmathey** [comment]
my bad.
