### ISSUE TITLE
Récupération du contenu

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/inyo#130]
# But de cette feature
Permettre de tester les besoins de récupération de contenu en développant le moins de choses possible.
# Besoin dans le back
Ajouté au items un type. Pour les deux types seront "DEFAULT" et "CONTENT_ACQUISITION".
# Comportement suivant validation de la tâche précédente
Lorsqu'une tâche est validée et que la tâche suivante est de type "CONTENT_ACQUISITION", le back ne devra pas envoyé d'email au client. Un email est envoyé a [yannick@inyo.me](mailto:yannick@inyo.me), [francois@inyo.me](mailto:francois@inyo.me) et [yann@inyo.me](mailto:yann@inyo.me). Avec le contenu suivant:
Sup les losers,

{{userEmail}} a une tâche en attente qui demande de la récupération de contenu. Le nom du projet est {{projectName}}. Le client est {{customerName}} email {{customerEmail}}.

Description de la tâche de récup:
{{description}}

Lien vers le projet:
{{url}}

A plus :*

#Interface
## interface permettant la création d'une tâche récupération de contenu
L'interface de création d'une tâche doit changer pour une modal. Voici le design:
![image](https://user-images.githubusercontent.com/971751/50548516-774c9200-0c4e-11e9-8d94-86067cbf279b.png)
## interface de tâche de récupération du contenu
![image](https://user-images.githubusercontent.com/971751/50549410-b2ee5880-0c5c-11e9-956a-fdf0bd05746e.png)
## Visualisation de récupération de contenu dans la vue projet
A faire

# Dropbox
## A l'inscription
Lorsqu'un user s'inscrit a inyo. Créer un dossier dans dropbox avec l'email de l'user et le partager avec lui.
## Récupération de contenu
Lorsqu'une nouvelle tâche de récupération est lancé ajoutez un dossier avec le nom du projet dans dropbox dans le dossier de l'utilisateur.
Si le contenu a récupérer n'est pas bien listé dans la description de la tâche contacté l'utilisateur pour connaitre les fichiers a récupérer.
Puis contacter le client par email et ajouter les fichiers au dropbox au fur et a mesure en laissant des commentaires dans la tâche au fur et a mesure.

Utiliser boomerang pour savoir si l'email a été consulté et pour relancer.

**Comment by yannickmathey** [comment]
Pour développer au plus vite cette option, et après discussion avec Yann et @YoruNoHikage je propose de partir de ce qui existe déjà au niveau UI. Voici ma proposition de design:

![capture d ecran 2019-01-03 a 11 27 54](https://user-images.githubusercontent.com/859119/50633216-ccd4b780-0f4a-11e9-9a39-47ef2e17280a.png)

**État 1:**
On ajoute seulement une checkbox en haut à droite pour créer un type de tâche différent.

**État 2:**
La chechbox est cochée. Le trigger change l'attribution de la tâche automatiquement (mais l'utilisateur peut décider de se la réattribuer). Sous la description un bouton apparaît pour permettre de lister les contenus à récupérer. Placeholder.

**État 3:**
Des contenus ont été ajoutés.
