### ISSUE TITLE
Morning email when no project

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#134]
**Is your feature request related to a problem? Please describe.**
I receive an email to tell me what to do today, but I have actually no ongoing project at all. The email content should be different

**Describe the solution you'd like**
Say something like "You have no current project: why not take some time to update your portfolio or learn new skills? Here some interesting links:" + links of blog post 

**Describe alternatives you've considered**
Ask the freelancer if everyhting is fine: he may have some projects actually but doesn't use our tool. We should try to contact him or convince him he should use Inyo.

**Comment by FranzPoize** [comment]
I don't think we should send an email every day if a user doesn't have any projects.

**Comment by yannickmathey** [comment]
If we have a list of useful blog posts / ressources, I think it is a good way to keep it go
