### ISSUE TITLE
User still doesn't know he has to create customer

### ISSUE THREAD

**Issue by YoruNoHikage** [byte-foundry/inyo#142]
**Describe the bug**
The `required` error has not been understood by a user. He thinks everything is okay but there is not customer selected.

**To Reproduce**
1. Go to create project page
2. Fill in the projects info but don't add nor select a customer
3. Try submitting the form.

**Expected behavior**
The `required` error should be above the `create customer` button, and maybe the placeholder color is too strong. (see screenshot ↓)

**Screenshots**
![image](https://user-images.githubusercontent.com/969003/50288394-1c54b700-0466-11e9-99aa-7b7e7cf50f05.png)

**Comment by yannickmathey** [comment]
The best solution could be to change the border-color of the concerned input (in addition to change the position of the error message of course)

**Comment by FranzPoize** [comment]
#95
