### ISSUE TITLE
Check infos before sending

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/inyo#15]
# Check info before quote delivery
User story
---
As a user I need my infos to be complete before I send a quote

Description of the behavior
---
When a user clicks on the send quote. We have to check that all the required info are populated in his company. If not we should display a modal where he can fill in the missing info. When he is done the quote should be sent.

Wireframe
---
![](https://i.imgur.com/SWM7By0.png)

**Comment by Aldrian** [comment]
Done.
