### ISSUE TITLE
Icon state after snooze

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#169]
**Is your feature request related to a problem? Please describe.**
When I snooze a task from the dashboard, it would be more comprehensible if the icon checkbox is replaced by the blue snooze icon (instead of disappearing)

**Describe the solution you'd like**
Once I click on the snooze icon, this one should dissapear, and then the checkbox is replaced by the snooze icon (the colored one, blue)

**Comment by FranzPoize** [comment]
this is not relevant
