### ISSUE TITLE
Edwige name is null

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#173]
**Describe the bug**
When the user receives the email from Edwige (during the onboarding), it misses a name. Edwige null is not a good name IMHO

**To Reproduce**
1. Do the onboarding as a user
2. Take the role of Edwige and write a comment
3. Receive the email from the user side

**Expected behavior**
If name is null, remove it. Or give Edwige a last name? Inyo?

**Screenshots**
![capture d ecran 2019-01-08 a 15 28 38](https://user-images.githubusercontent.com/859119/50836758-49580380-135a-11e9-8dac-1f633faaf460.png)

**Comment by yannPrototypo** [comment]
The bug is partly solved. The name "Edwige null" still appears during the onboarding but not anymore on "normal" projects.
