### ISSUE TITLE
Wrong link in the task confirmation email sent by Edwige during the onboarding

### ISSUE THREAD

**Issue by yannPrototypo** [byte-foundry/inyo#179]
Can't connect to the project "Bienvenu" from the task confirmation email sent by Edwige.

Link on the "Voir les tâches restantes" button:
http://quote.inyo.me/wf/click?upn=voHUJLKWRTOMa8Z5VBwJ8qjyVJYZM-2FjqOemhC9KM5UMq8xZ4jsQSVvZhYrFGD-2FUuhe5vbQqw5qFycvOqY9Hm2FAvsEMjvj7I-2BzBAK9gtCaho1jupMRIkznHlYyC5ChSpL6iVmrHpAzGPjjnehykqzeuQWSAkzJVqXdCaeMtEjJWS13vaVXwCpUekhZnK0a7MmF4yftQO9rzFFHo3SsQ8PLW13GGVwPdF9YoUMGn6ajI-3D_XBOy0Vq7l6Sc90EKxgnqPFdKX44kNYZrTeBJmr2QdQUikNEfWkDltmM7QUgYuVbaorO-2FY1Az7Y6XaykqJ1cSirmA-2BfzZwhxYRpVejO6VDH0AuKal2DCyfeuBByPLgovSe07bcGVAb-2BhMTpEcOpGIz3-2FjylX9oePZco30vUlILG28EYSqwVZZyqjR7J5kFw9NstP8oDD497WN6J1-2Fo0RDH-2FxB3MTPml-2BwDq2XIwdoKkEGdYpRzUZLnF-2Fk4vvmzxApr79Hr-2FEjZNM0A-2BpeU1ZxYjj9HV3YbDFIX9nNFBsxSmMqRREX1zUA8lh-2FZ5QjrZSKAonIfGEfNSXPy2OwAoSeIjCDhLFBsCGe-2Fdx80rkXObvoPDNyrnKLuKPqSsfGk9hDDR-2B8aITO8c-2Bx1wFKbReckA-3D-3D

**Comment by FranzPoize** [comment]
Link sent to user is a customer-view url not a project-see url.
