### ISSUE TITLE
Reset password link redirects to app

### ISSUE THREAD

**Issue by yannPrototypo** [byte-foundry/inyo#186]
Can't reset a password.

1. Go to 'https://beta.inyo.me/auth/sign-in'
2. Click on 'Mot de passe oublié ?'
3. Enter an email address linked to an account
4. Click the password reset link in the email
5. Redirection to a sign in page (attached picture) where you can't create a new password. No "Mot de passe oublié ?" link on this page.

Link in the email:
https://app.inyo.me/auth/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inlhbm5AcHJvdG90eXBvLmlvIiwiaWF0IjoxNTQ3MTE0ODY5LCJleHAiOjE1NDcxMjIwNjl9.GpZq05HHz1EEjTH0Hio3IQyQ9x0QKJxNrx8SZdbDZnc

![image](https://user-images.githubusercontent.com/17646529/50961890-36b00c80-14c9-11e9-97e8-d9e21e73da9d.png)

**Comment by YoruNoHikage** [comment]
Hotfixed on master, the link is now correct.
