### ISSUE TITLE
typos in email notifying a task completed

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#24]
"Bonjour Name Firstname"
>> We should switch the order first and last name

"vient de finir la tâche Benchmark de votre projet ."
>> We should remove the space before the dot.

"Vous pouvez accéder n'importe quand au devis en cliquant sur ce bouton:"
+
"Consulter le devis"
>> We shouldn't mention the quote here, but something related to a "tasks list" or something like that.

"Si vous avez des questons n'hésitez pas a revenir vers moi
 Cordialement,
 Edwige de Inyo.Si vous avez des questons n'hésitez pas a revenir vers moi"
>> "Questions" is misspelled (i is missing) and it is "à revenir" with an acute diacritic.
>> We repeat twice this sentence. The second one can be removed.

**Comment by FranzPoize** [comment]
For the name firstname lastname check that the name you entered in the app are in the right order. We put them in the right order from what I can tell
![image](https://user-images.githubusercontent.com/971751/47783741-d1d77980-dd03-11e8-9ac0-0e93904484a8.png)
Rest is fixed.
