### ISSUE TITLE
When adding content to acquire you can't click on the task anymore to blur the input

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/inyo#240]
**Describe the bug**
When adding content to acquire you can't click on the task anymore to blur the input

**To Reproduce**
1. Open a task
2. Make it content acquisition
3. start adding a file to the list
4. click anywhere on the task

**Expected behavior**
It should blur the input

**Additional context**
Probably due to the drag and drop behavior

**Comment by YoruNoHikage** [comment]
I removed the fixed label since 1574826 blocked the `<Creatable />`, was impossible to reproduce locally but easily reproduced on dev/beta.
