### ISSUE TITLE
Missing freelance infos on client view

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#248]
**Describe the bug**
Some project have information about the freelancer, some others don't.

**To Reproduce**
works:
https://beta.inyo.me/app/projects/cjqso31362jgg08034gnxwmq6/view/dd2b8a45-4ecc-4535-b41f-7614847b9371?utm_campaign=website&utm_source=Sendgrid&utm_medium=email

doesn't work:
https://beta.inyo.me/app/projects/cjr2cu5s33k4b0803jb1guvs9/view/8d4cf954-8331-45ed-9431-649b7431b975?utm_campaign=website&utm_source=Sendgrid&utm_medium=email (edited) 

**Expected behavior**
All client view should display information about the freelancer

**Additional context**
One of this project is an onboarding, the second one is not. Dunno if it matters.

**Comment by YoruNoHikage** [comment]
Fixed in #229
