### ISSUE TITLE
Client answers to Edwige fail

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#28]
After I sent the email as a client, I received this email:

> This is the mail system at host mo**.mail-out.ovh.net.
> 
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.
> 
>                    The mail system
> 
> <****@inyo.me>: host redirect.ovh.net[*********] said: 500 Domain not in
>     ovh system (in reply to RCPT TO command)

**Comment by FranzPoize** [comment]
We need to setup gsuite
