### ISSUE TITLE
HT price on QuoteCard is different from the actual price on the quote view

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#29]
I create a quote. Its total amount is 2 975 € HT. But when I look at the quote's dashboard, its amount is 4550€ HT.

Same quotes, different HT totals:

![capture d ecran 2018-10-30 a 21 05 07](https://user-images.githubusercontent.com/859119/47746946-88494900-dc87-11e8-9e6a-6ad7b6b62344.png)
![capture d ecran 2018-10-30 a 21 05 12](https://user-images.githubusercontent.com/859119/47746947-88e1df80-dc87-11e8-9e23-256a626cd0c7.png)

**Comment by FranzPoize** [comment]
on master
