### ISSUE TITLE
Implémenter interface d'ajout client

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/inyo#296]
Dans invision pour l'instant c'est fait en un seul écran. Il faudrait que ca soit plus comme aujourd'hui je pense, sinon ca risque de prêter a confusion.

**Comment by YoruNoHikage** [comment]
- [x] Ajout modale avec un autocomplete et un bouton nouveau client
- [x] Formulaire ajout client

Temps : 1

**Comment by yannickmathey** [comment]
Lorsqu'un client est sélectionné le form du bas disparait et le titre du bouton devient 'valider'

Avant sélection:

<img width="819" alt="capture d ecran 2019-02-18 a 17 23 34" src="https://user-images.githubusercontent.com/859119/52964199-0bf78480-33a2-11e9-9e21-3e9b317a9ea5.png">

Après sélection:

<img width="825" alt="capture d ecran 2019-02-18 a 17 23 43" src="https://user-images.githubusercontent.com/859119/52964230-1b76cd80-33a2-11e9-9c27-d5cfe4c4bdcc.png">

Si l'on clique sur la croix: le client est déselectionné et retour à l'étape d'avant
