### ISSUE TITLE
Layout nouvelle page projet

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/inyo#297]
En gros c'est mettre en place le nouveau design system. Pour l'instant la partie du haut est pas a mettre (Vue principale)

**Comment by YoruNoHikage** [comment]
- [x] Ajout/intégration de la sidebar
- [x] Ajout input deadline #299 
- [x] Ajout dupliquer le projet (avec une modale pour le nouveau nom ?

Temps : 2
