### ISSUE TITLE
Contact first and last name are not displayed on the quote view

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#31]
Even if the CustomerNameAndAddress component seems to want to display these informations, nothing comes up on the front:

```
<ContactName>
     {firstName} {lastName}
</ContactName>
```
line 44:
https://github.com/byte-foundry/inyo/blob/master/src/components/CustomerNameAndAddress/index.js

**Comment by FranzPoize** [comment]
on master

**Comment by Aldrian** [comment]
Fixed in e53cea2b68d73a3b868377c2f98a91cb47515413
