### ISSUE TITLE
Better visualisation of amendment

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/inyo#34]
# Ideas
![image](https://user-images.githubusercontent.com/971751/47790867-8aa7b380-dd18-11e8-8ad6-746dc0914e2b.png)
I'll update with the item view

**Comment by yannickmathey** [comment]
New infos should not be relative but absolute.
16,5 days instead of +1,5 days to avoid misunderstanding

We can also group them in a div under the current infos with an obvious label/title
