### ISSUE TITLE
Scroll does not work in comments section

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#482]
It looks like a browser / OS issue since it works on other computers.

Tested with Chrome Version 73.0.3683.103 (Build officiel) (64 bits)
Os X El Capitan 10.11.4 (15E65)

I can't scroll with my trackpad

**Comment by yannickmathey** [comment]
It happens on all my devices now (Osx Chrome)

**Comment by yannickmathey** [comment]
I remove the 'critical' label since it happened on other websites

**Comment by FranzPoize** [comment]
Is that still a problem ?
