### ISSUE TITLE
I can't comment anymore a task

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#53]
On both sides, user or client, I can't comment a task. The popup opens, I can write my comment, but when I want to validate it I have this error in the console:

![capture d ecran 2018-11-09 a 12 17 47](https://user-images.githubusercontent.com/859119/48261439-5f5f4b80-e41f-11e8-9894-43d08554a027.png)

**Comment by YoruNoHikage** [comment]
It should be fixed now
