### ISSUE TITLE
Project is not marked as finished when all tasks are done

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#58]
Create a project.
Mark all tasks as done.
The progress bar is 100% but the project stays in the "en cours" column

**Comment by FranzPoize** [comment]
Probably better to do this in backend

**Comment by FranzPoize** [comment]
I'm opening a feature request for frontend to display something once the project is done

**Comment by yannickmathey** [comment]
It is not only on the project page, but also move the project to the third column on dashboard. Probably irrelevant if we change the current dashboard design in the future (but I guess we'll still have this kind of kanban view somewhere)
