### ISSUE TITLE
Can't reply to a comment

### ISSUE THREAD

**Issue by yannPrototypo** [byte-foundry/inyo#649]
Cannot reply to a comment from the client side.

The error is:
Uncaught TypeError: Cannot read property 'type' of undefined
   at e.setFieldValue (onloadwff.js:71)
   at HTMLFormElement.formKeydownListener (onloadwff.js:71)

I reached the task from the link in the email notification.

**Comment by FranzPoize** [comment]
Seems the task is in a project but the customer is not the customer of the project

**Comment by FranzPoize** [comment]
https://beta.inyo.me/app/1241be7f-3959-456f-b061-d304e5936ede/tasks/cjxud0o7qpmr80758notcpdev?utm_campaign=website&utm_source=Sendgrid&utm_medium=email
