### ISSUE TITLE
Loading chunk css and js are failing

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/inyo#663]
We should find a way to mitigate the issue

**Comment by FranzPoize** [comment]
https://sentry.io/organizations/prototypo/issues/1107390107/?project=1307916&query=is%3Aunresolved

**Comment by FranzPoize** [comment]
https://sentry.io/organizations/prototypo/issues/1108548695/?project=1307916&query=is%3Aunresolved

**Comment by yannickmathey** [comment]
It also happened after I tried to edit a tag from itemView

**Comment by FranzPoize** [comment]
On sait d'ou ca vient faut juste qu'on le traite
