### ISSUE TITLE
Remaining days calculation in project seems false

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#672]
- Add some tasks in a project with estimated durations (i.e. 16 hours)
- Add a deadline (i.e 3 days after)

The calculation will be wrong for 2 reasons:
- the deadline is set for the begining of the day
- idk the second reason but it adds at least 2 days more than it should do. 

In my case it was: 15h of cumulated tasks, Deadline in 2 days (16h left) and the margin was -3,16 days.

**Comment by FranzPoize** [comment]
Have to do same thing for tasks now.
