### ISSUE TITLE
New task view

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/inyo#686]
Just a list of issue that will be solved by the new task view

**Comment by FranzPoize** [comment]
#654

**Comment by FranzPoize** [comment]
![new_project_view](https://user-images.githubusercontent.com/971751/61728881-58daef00-ad76-11e9-9a7c-39240794eaaa.png)

**Comment by yannickmathey** [comment]
@FranzPoize I have added an icon on hover to add tags quicker on the project view: 
![Capture d’écran 2019-07-24 à 16 41 14](https://user-images.githubusercontent.com/859119/61803178-ffd09100-ae31-11e9-9064-a02e47560417.png)

Complete design here: https://www.figma.com/file/5oL1DvaloiQ9aOcuZxRxQA/UI-Inyo?node-id=13%3A2710
