### ISSUE TITLE
Missing url in invoice reminder email

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#692]
the url of the task (or the direct url of the file?) is missing:

![Capture d’écran 2019-07-24 à 09 31 54](https://user-images.githubusercontent.com/859119/61773900-03debd80-adf6-11e9-9605-0c4b71b40bf6.png)

**Comment by FranzPoize** [comment]
Il semble que le problème soit plus que l'on peut activer une tâche facture sans attachments

**Comment by FranzPoize** [comment]
check all the emails
