### ISSUE TITLE
Missing task's name in collaborator’s notifications 

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#727]
A collaborator marked a task as done but I don’t have its title. 

“Yann Guillet a validé la tâche .”

**Comment by YoruNoHikage** [comment]
We don't have any information on the user's gender / title, it should be discussed whether we want to ask for it and if so, when.

**Comment by yannickmathey** [comment]
I meant title of the task

“Yann Guillet a validé la tâche .”

Quelle tâche?
