### ISSUE TITLE
Email du matin

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/inyo#81]
## Qu'est que l'on veut qu'il se passe ?

On veut que chaque utilisateur reçoive chaque matin 5 min avant l'heure ou il commence a travailler un email qui lui donne toutes les tâches qu'il peut réaliser aujourd'hui.

## Tâche active

La tâche active est la première tâche non validé dans un projet

## Projet Actif

Les projets actifs sont les projets dont la tâche active est une tâche dont le reviewer est USER

## Comment doivent être trier les tâches

Les tâches a trier sont les tâches des projets actifs. Elles sont triés de la manière suivante:

- Un score est attribué a chaque tâche. Ce score est calculé comme suivant

`TempsEnHeureJusquaDeadline - TempsEnHeuresTâchesSuivantes - TempsEnHeureDeLaTache`

- TempsEnHeureJusquaDeadline = Temps en heure entre aujourd'hui et la deadline
- TempsEnHeuresTâchesSuivantes = somme des temps en heures des tâches non finies précédentes
- TempsEnHeureDeLaTache = temps en heure de la tâche à scorer
- Les tâches sont ensuite ordonnées dans par leur score de manière croissante (plus petit score en premier)

## Comment choisir les tâches

Les trois tâches ayant le plus haut scores sont automatiquement sélectionnées. Si la somme des temps en heures de ces trois tâches est inférieur au temps de travail de l'user rajouté des tâches jusqu'a que la somme des temps de travail soit supérieur au temps de travail journalier de l'utilisateur.

## Combien de tâches ?

L'utilisateur doit recevoir X tâches. X ≥ 3 et X ≤8.

## Texte de l'email

```
Salut {{user}}

Voilà les tâches sur lesquelles tu pourras te concentrer aujourd'hui:
{{#each project}}
* {{this.name}}
  {{#each this.sections}}
    {{#each this.items}}
      * <a href={{this.url}}>{{this.name}} {{this.unit * 8}} heures</a>
    {{/each}}
  {{/each}}
{{/each}}

Passe une bonne journée,

Edwige de Inyo
````

**Comment by YoruNoHikage** [comment]
Almost everything is ready in byte-foundry/inyo-api@1b0e93d, untested.
I'll add some tests to fix bugs and mistakes
