### ISSUE TITLE
Error message when reconnecting

### ISSUE THREAD

**Issue by yannPrototypo** [byte-foundry/inyo#862]
When the tab with Inyo has been left open and the computer went offline, this error message happens when reconnecting: "Error : Network error : Failed to fetch"

This problem was solved and reappeared on October the 8th.

![image (11)](https://user-images.githubusercontent.com/17646529/66467306-89344e80-ea84-11e9-824a-d6712be7d915.png)

**Comment by FranzPoize** [comment]
The Whoops is the thread pool server error. Anyway we shouldn't throw on polling when there's data
