### ISSUE TITLE
Create Client UX should be improved

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#91]
**Is your feature request related to a problem? Please describe.**
Some user don't know how to create a new client, because they don't know they have to press Enter

**Describe the solution you'd like**
We should add a button or suggest to press Enter

**Describe alternatives you've considered**
The current input could be only to chose an existing client and we could add a "Create client" link under to display the form.

**Comment by FranzPoize** [comment]
We should also add a small message about privacy
