### ISSUE TITLE
Grosse passe sur erreur formulaire

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/inyo#95]
Vérifier tous les formulaires et harmoniser l'affichage des erreurs.
Front loading a faire: Lister tous les formulaires.

**Comment by yannPrototypo** [comment]
Textes différents lorsqu'on entre un format d'email non valide:
Se connecter:
![image](https://user-images.githubusercontent.com/17646529/52413171-1cc21380-2ae1-11e9-8a39-6b9b1248bbea.png)
Créer un compte:
![image](https://user-images.githubusercontent.com/17646529/52414965-09657700-2ae6-11e9-91c9-9e6352fd0dd0.png)
Création d'un client:
![image](https://user-images.githubusercontent.com/17646529/52415153-88f34600-2ae6-11e9-849d-effd2d14e240.png)

On peut dire "Le format de l'email doit être valide".
