### ISSUE TITLE
'Remove section' button

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/inyo#99]
**Is your feature request related to a problem? Please describe.**
On a started project, we shouldn't display the 'Remove Section' button if we can't remove the section.

**Describe the solution you'd like**
We can remove a section when none of the tasks have been validated (but before removing the section, the user should add a comment or something like that).

**Describe alternatives you've considered**
In the meantime, we could simply hide this button, since it does not have any effect for the moment (but it should).

**Additional context**
This was tested on dev on a started project. This suggestion does not apply on a project draft.

**Comment by yannPrototypo** [comment]
We can still delete a section if the project has started.
